export let Charges = {
    list : [
            { value: 'Aggravated Assault', label: 'Aggravated Assault' },
            { value: 'Aiding and Abetting', label: 'Aiding and Abetting' },
            { value: 'Arson', label: 'Arson' },
            { value: 'Assault / Battery', label: 'Assault / Battery' },
            { value: 'Attempt', label: 'Attempt' },
            { value: 'Bribery', label: 'Bribery' },
            { value: 'Burglary', label: 'Burglary' },
            { value: 'Card Fraud', label: 'Card Fraud' },
            { value: 'Child Abandonment', label: 'Child Abandonment' },
            { value: 'Child Abuse', label: 'Child Abuse' },
            { value: 'Child Pornography', label: 'Child Pornography' },
            { value: 'Computer Crime', label: 'Computer Crime' },
            { value: 'Conspiracy', label: 'Conspiracy' },
            { value: 'Criminal Contempt of Court', label: 'Criminal Contempt of Court' },
            { value: 'Cyberbullying', label: 'Cyberbullying' },
            { value: 'DUI / DWI', label: 'DUI / DWI' },
            { value: 'Disorderly Conduct', label: 'Disorderly Conduct' },
            { value: 'Disturbing the Peace', label: 'Disturbing the Peace' },
            { value: 'Domestic Violence', label: 'Domestic Violence' },
            { value: 'Drug Manufacturing', label: 'Drug Manufacturing' },
            { value: 'Drug Possession', label: 'Drug Possession' },
            { value: 'Drug Trafficking / Distribution', label: 'Drug Trafficking / Distribution' },
            { value: 'Embezzlement', label: 'Embezzlement' },
            { value: 'Extortion', label: 'Extortion' },
            { value: 'Forgery', label: 'Forgery' },
            { value: 'Fraud', label: 'Fraud' },
            { value: 'Harassment', label: 'Harassment' },
            { value: 'Hate Crimes', label: 'Hate Crimes' },
            { value: 'Homicide', label: 'Homicide' },
            { value: 'Identity Theft', label: 'Identity Theft' },
            { value: 'Insurance Fraud', label: 'Insurance Fraud' },
            { value: 'Kidnapping', label: 'Kidnapping' },
            { value: 'Manslaughter', label: 'Manslaughter' },
            { value: 'Medical Marijuana', label: 'Medical Marijuana' },
            { value: 'Minor in Possession', label: 'Minor in Possession' },
            { value: 'Money Laundering', label: 'Money Laundering' },
            { value: 'Murder: First-degree', label: 'Murder: First-degree' },
            { value: 'Murder: Second-degree', label: 'Murder: Second-degree' },
            { value: 'Perjury', label: 'Perjury' },
            { value: 'Probation Violation', label: 'Probation Violation' },
            { value: 'Prostitution', label: 'Prostitution' },
            { value: 'Public Intoxication', label: 'Public Intoxication' },
            { value: 'Pyramid Schemes', label: 'Pyramid Schemes' },
            { value: 'Racketeering / RICO', label: 'Racketeering / RICO' },
            { value: 'Rape', label: 'Rape' },
            { value: 'Robbery', label: 'Robbery' },
            { value: 'Securities Fraud', label: 'Securities Fraud' },
            { value: 'Sexual Assault', label: 'Sexual Assault' },
            { value: 'Shoplifting', label: 'Shoplifting' },
            { value: 'Solicitation', label: 'Solicitation' },
            { value: 'Stalking', label: 'Stalking' },
            { value: 'Statutory Rape', label: 'Statutory Rape' },
            { value: 'Tax Evasion / Fraud', label: 'Tax Evasion / Fraud' },
            { value: 'Telemarketing Fraud', label: 'Telemarketing Fraud' },
            { value: 'Theft', label: 'Theft' },
            { value: 'Vandalism', label: 'Vandalism' },
            { value: 'White Collar Crimes', label: 'White Collar Crimes' },
            { value: 'Wire Fraud', label: 'Wire Fraud' }
    ]
};